# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mg-dyiz9SLM27Fy62S75oJoO2oLGpRQB
"""

import discord
from discord.ext import commands
import spacy
import random

# Load English language model
nlp = spacy.load("en_core_web_sm")

# Define responses to different types of input
responses = {
    "greetings": ["Hello!", "Hi there!", "Hey!"],
    "farewell": ["Goodbye!", "See you later!", "Bye!"],
    "thanks": ["You're welcome!", "No problem!", "Anytime!"],
    "default": ["I'm sorry, I don't understand.", "Could you please rephrase that?", "I'm just a simple bot."]
}

# Create a bot instance with intents
intents = discord.Intents.default()
intents.messages = True
intents.guilds = True
intents.members = True
intents.presences = True

bot = commands.Bot(command_prefix='#', intents=intents)

@bot.event
async def on_ready():
    print('Bot is ready!')
    print('Logged in as', bot.user.name)

@bot.command()
async def chat(ctx, *, input_text):
    response = get_response(input_text)
    await ctx.send(response)

def get_response(input_text):
    # Process the input text using spaCy
    doc = nlp(input_text.lower())

    # Check for specific patterns in the input and generate a response
    if any(token.text in ["hello", "hi", "hey"] for token in doc):
        return random.choice(responses["greetings"])  # Randomly select a greeting response
    elif any(token.text in ["bye", "goodbye"] for token in doc):
        return random.choice(responses["farewell"])  # Randomly select a farewell response
    elif any(token.text in ["thanks", "thank", "thank you"] for token in doc):
        return random.choice(responses["thanks"])  # Randomly select a thanks response
    elif "how are you" in input_text:
        return "I'm just a bot, so I don't have feelings, but I'm here to help!"
    elif "weather" in input_text:
        return "I'm not a weather bot, but you can check the weather using various online services."
    elif "help" in input_text:
        return "Sure, I'm here to help! What do you need assistance with?"
    elif "who are you" in input_text:
        return "I'm a friendly chatbot here to assist you with any questions or tasks you have."
    elif "tell me a joke" in input_text:
        return "Why don't scientists trust atoms? Because they make up everything!"
    elif "tell me about yourself" in input_text:
        return "I'm just a simple chatbot created to provide assistance and engage in conversation."
    elif "how old are you" in input_text:
        return "I don't have an age. I'm just a virtual assistant!"
    elif "where are you from" in input_text:
        return "I exist in the digital world, so you could say I'm from the internet!"
    elif "favorite color" in input_text:
        return "I don't have eyes, so I don't have a favorite color!"
    elif "what can you do" in input_text:
        return "I can provide information, answer questions, tell jokes, and more. Just ask!"
    elif "do you sleep" in input_text:
        return "Nope, I'm available 24/7 to assist you!"
    elif "favorite food" in input_text:
        return "I don't eat, but I've heard good things about pizza!"
    elif "recommend a restaurant" in input_text:
        return "I can suggest some options if you'd like! Pizza Hut, Kentucky Fried Chicken, and McDonald's are delicious choices!"
    elif "recipe" in input_text:
        return "I am just a bot. I do not know how to cook nor any recipes. :("
    elif "hungry" in input_text or "food" in input_text:
        return "I recommend the restaurant, Khan's Grill. Delicious  Mongolian food there!"
    elif "burger" in input_text:
        return "Burgers are a classic choice! My favorite are veggie burgers."
    elif "pizza" in input_text:
        return "Pizza is always a crowd-pleaser! Pepperoni is my favorite."
    elif "taco" in input_text:
        return "Tacos are delicious! I like mine crunchy!"
    elif "sushi" in input_text:
        return "Sushi is a great choice! I like sushi, too."
    else:
        return random.choice(responses["default"])  # Randomly select a default response

# Run the bot
bot.run('my_secret_key')